theme: jekyll-theme-cayman
title: Matt Edwards
description: Data Scientist at Pilot Flying J
avatar: https://media.licdn.com/dms/image/C4E03AQFB1KaVp6dxsA/profile-displayphoto-shrink_200_200/0?e=1582156800&v=beta&t=hw-_V_W65y6L4a_3QyimaRgdGF02K_n34h4iy2PAj9I
